Vagrant.configure("2") do |config|
  config.vm.box = ENV.fetch("PRPLMESH_BOX", "prplmesh/lab-0829")
  config.vm.hostname = "prplmesh-lab"
  config.vm.boot_timeout = 1800

  host_ip = ENV.fetch("PRPLMESH_UI_HOST_IP", "127.0.0.1")
  topology_port = ENV.fetch("PRPLMESH_TOPOLOGY_HOST_PORT", "8090").to_i
  ui_port = ENV.fetch("PRPLMESH_UI_HOST_PORT", "8091").to_i
  config.vm.network "forwarded_port", guest: 8090, host: topology_port,
                    host_ip: host_ip, auto_correct: false
  config.vm.network "forwarded_port", guest: 8091, host: ui_port,
                    host_ip: host_ip, auto_correct: false

  config.ssh.username = "vagrant"
  config.ssh.insert_key = true

  config.vm.provider "virtualbox" do |vb|
    vb.name = ENV.fetch("PRPLMESH_VM_NAME", "prplmesh-lab-0829")
    vb.memory = ENV.fetch("PRPLMESH_VM_MEMORY_MB", "8192")
    vb.cpus = ENV.fetch("PRPLMESH_VM_CPUS", "6")
    vb.customize ["modifyvm", :id, "--nested-hw-virt", "on"]
    vb.customize ["modifyvm", :id, "--ioapic", "on"]
  end
end
