export const revision = '68e9ee4a9233f9d9949cbd18b4a0de6d036f253b';
export const source = (path: string) =>
  `https://github.com/boardfarmdevs/prplmesh-lab/${path ? 'blob' : 'tree'}/${revision}/${path}`;

export type Entry = {
  title: string;
  color: string;
  kind: string;
  summary: string;
  description: string;
  properties: [string, string][];
  related: string[];
  sources: string[];
  note?: string;
};

function entry(
  title: string,
  color: string,
  kind: string,
  summary: string,
  description: string,
  properties: [string, string][],
  related: string[],
  sources = ['reference/platform/software-architecture.md'],
  note?: string,
): Entry {
  return {
    title,
    color,
    kind,
    summary,
    description,
    properties,
    related,
    sources,
    note,
  };
}

export const entries: Record<string, Entry> = {
  gateway: entry(
    'prpl-controller',
    'blue',
    'Native Linux · LXD container',
    'Controller and colocated Agent-1 share one mesh device.',
    'Native prplMesh runs independently of RDK: its controller, agent, per-radio fronthaul workers and IEEE 1905 transport operate real hostapd and Linux wireless interfaces.',
    [
      ['Roles', 'Controller + Agent-1'],
      ['Bridge', 'br-lan'],
      ['Radios', 'Three hwsim PHYs per mesh device'],
    ],
    ['controller', 'agent', 'database', 'radios', 'bridge'],
  ),
  controller: entry(
    'beerocks_controller',
    'blue',
    'Native EasyMesh controller',
    'Maintains the authoritative model and native command transactions.',
    'Topology, AP/client metrics and steering outcomes originate in prplMesh. The external optimizer requests steering through a bounded adapter; it does not substitute its own associations for native state.',
    [
      ['Transport', 'ieee1905_transport'],
      ['Northbound model', 'Ambiorix / ubus DataElements'],
      ['State', 'Native in-memory model; no RDK MariaDB'],
    ],
    ['database', 'ieee1905', 'agent', 'optimizer'],
  ),
  database: entry(
    'NBAPI / DataElements',
    'blue',
    'Ambiorix + ubus',
    'Native device, radio, BSS and station ownership records.',
    'The adapter reads Device.WiFi.DataElements using ubus. A metrics update must not invent an association. Physical station links, native ownership and WLAN traffic are checked separately.',
    [
      ['Model', 'Device → Radio → BSS → STA'],
      ['Mesh inventory', 'Five devices / fifteen radios'],
      ['Client pool', '100 provisioned; room controls active subset'],
    ],
    ['controller', 'cli', 'tests'],
    ['reference/observability/topology-adapter.md'],
  ),
  cli: entry(
    'Controller UI + adapter',
    'blue',
    'Go WebUI · normalized native APIs',
    'The same visual topology language as the RDK lab, backed by prplMesh.',
    'The guest WebUI reads the loopback adapter, which normalizes native NBAPI state. Host-facing ports belong to the named VM and are not fixed to a particular developer machine.',
    [
      ['Guest topology', 'HTTP :8091'],
      ['Guest adapter', 'Loopback :8092'],
      ['Host ports', 'Selected by lab-config.sh'],
    ],
    ['database', 'controller', 'room'],
    ['reference/observability/topology-adapter.md', 'docs/operations.md'],
    'This public explorer is illustrative. It never polls a running lab.',
  ),
  agent: entry(
    'beerocks_agent',
    'cyan',
    'Platform + backhaul manager',
    'Coordinates a device’s radios and translates controller requests.',
    'Agent-1 is colocated with the controller. Four external agents run in prpl-agent-01 through prpl-agent-04. Per-radio fronthaul processes handle AP operations and reporting.',
    [
      ['Workers', 'beerocks_fronthaul per radio'],
      ['Uplink', '5 GHz backhaul station'],
      ['Control', 'Native IEEE 1905 CMDUs'],
    ],
    ['fronthaul', 'hostapd', 'ieee1905', 'backhaul'],
  ),
  ieee1905: entry(
    'ieee1905_transport',
    'blue',
    'IEEE 1905.1 control plane',
    'Transports native EasyMesh messages over the mesh.',
    'The broker and local Unix sockets connect native processes. Autoconfiguration, topology, metrics and steering messages cross the wireless backhaul using EtherType 0x893a.',
    [
      ['Local broker', '/tmp/beerocks/uds_broker'],
      ['Onboarding', 'Autoconfiguration + WSC M1/M2'],
    ],
    ['controller', 'agent', 'backhaul'],
    undefined,
    'A 1905 ACK alone does not prove a successful roam.',
  ),
  hostapd: entry(
    'hostapd + supplicant',
    'blue',
    'Native AP and station state machines',
    'Own real authentication, beaconing, association and BTM exchanges.',
    'prplMesh uses its NL80211 backend and hostap control sockets. Unlike RDK OneWifi, these are standalone native hostapd and wpa_supplicant processes.',
    [
      ['APs', 'hostapd'],
      ['Stations', 'wpa_supplicant'],
      ['Kernel', 'nl80211 / cfg80211 / mac80211'],
    ],
    ['agent', 'hal', 'supplicant', 'fronthaul'],
  ),
  hal: entry(
    'NL80211 backend',
    'blue',
    'prplMesh BWL / hostap control',
    'Connects native fronthaul workers to Linux Wi-Fi.',
    'The lab uses the native NL80211 backend, not dummy radios or an RDK Wi-Fi HAL. Hostap control and nl80211 provide events and measurements.',
    [
      ['Backend', 'NL80211'],
      ['Kernel radios', 'mac80211_hwsim'],
    ],
    ['hostapd', 'hwsim', 'radios'],
  ),
  radios: entry(
    'Three-PHY mesh device',
    'purple',
    'Container radio ownership',
    'Each prpl mesh device owns separate 2.4, 5 and 6 GHz PHYs.',
    'Fronthaul workers use wlan0, wlan2 and wlan4. A backhaul station VIF shares the 5 GHz PHY. This differs from RDK’s single-wiphy projection.',
    [
      ['2.4 GHz', 'wlan0'],
      ['5 GHz', 'wlan2; wlan3 backhaul station'],
      ['6 GHz', 'wlan4'],
      ['Pool', '100 client radios; room presence does not resize the pool'],
    ],
    ['hwsim', 'fronthaul', 'backhaul'],
    ['scripts/radio-lab.sh', 'reference/platform/software-architecture.md'],
  ),
  extender: entry(
    'Four external agents',
    'cyan',
    'prpl-agent-01 … prpl-agent-04',
    'Native agent containers with wireless uplinks and tri-band fronthaul.',
    'Extenders bridge downstream client traffic across authorized four-address wireless backhaul. No extra wired LAN path is added to fake connectivity.',
    [
      ['Count', 'Four'],
      ['Per agent', 'Three PHYs and native fronthaul workers'],
      ['Layouts', 'Star, branch, chain; room-dependent backhaul behavior'],
    ],
    ['agent', 'fronthaul', 'backhaul', 'bridge'],
  ),
  bridge: entry(
    'br-lan + WDS',
    'blue',
    'Wireless data plane',
    'Carries client traffic through one or more upstream agents.',
    'Four-address forwarding preserves downstream station addresses. Management Ethernet is not evidence that the Wi-Fi path works; tests bind traffic to the WLAN interface.',
    [
      ['LAN', 'br-lan'],
      ['Validation', 'Physical BSSID + native owner + WLAN ping'],
    ],
    ['backhaul', 'client', 'wan', 'tests'],
  ),
  backhaul: entry(
    'Wireless backhaul',
    'cyan',
    '5 GHz · four-address forwarding',
    'Carries both EasyMesh control and downstream client traffic.',
    'A station associates with its parent AP and joins the bridged path. Geometry rooms test branch formation, proactive parent handover and isolation/recovery. This illustrative topology selector does not change a lab.',
    [
      ['Station VIF', 'wlan3'],
      ['Backhaul AP', 'wlan2.1'],
      ['SSID', 'mesh_backhaul'],
    ],
    ['agent', 'bridge', 'ieee1905', 'room'],
    ['reference/rooms/catalog.md'],
  ),
  fronthaul: entry(
    'beerocks_fronthaul',
    'cyan',
    'Per-radio workers + client-facing BSSs',
    'Provides private and IoT service through native AP processes.',
    'Each device has a fronthaul worker per band. Metrics and native BTM requests pass through this layer to hostapd.',
    [
      ['SSIDs', 'private_ssid · iot_ssid'],
      ['Bands', '2.4 / 5 / 6 GHz'],
    ],
    ['hostapd', 'agent', 'client', 'radios'],
  ),
  client: entry(
    'WLAN client pool',
    'pink',
    '100 provisioned LXD containers',
    'Rooms activate a subset without rebuilding or resizing the lab.',
    'Lean client images contain real station software. The default room uses twenty clients; the fifty-client room exercises a larger subset. Inactive clients stay provisioned but presence controls disconnect and isolate their radio paths.',
    [
      ['Interface', 'wlan0'],
      ['Control', 'WNM-enabled wpa_supplicant'],
      ['Default room', '20 active / 100 provisioned'],
      ['Management', 'Not the tested WLAN data path'],
    ],
    ['supplicant', 'room', 'medium', 'dhcpclient'],
    ['docs/build/vm.md', 'reference/rooms/catalog.md', 'scripts/radio-lab.sh'],
  ),
  supplicant: entry(
    'wpa_supplicant',
    'pink',
    'Real client station process',
    'Handles association, scans and native BSS transition requests.',
    'The client decides how to respond to BTM. Tests record the request, physical owner, band, model update and delivered traffic rather than equating command submission with success.',
    [
      ['Control', 'wpa_cli'],
      ['BTM', '802.11v / WNM'],
      ['Scan evidence', 'Received beacon cache, not geometry scores'],
    ],
    ['11v', '11k', '11r', 'band'],
    ['reference/optimizer/band-steering.md'],
  ),
  '11v': entry(
    '802.11v BTM',
    'pink',
    'Native steering action',
    'Source AP requests a BSS transition.',
    'Controller and agent deliver the command to hostapd. The real client responds and may reassociate. Timed verification is separate from policy hold/dwell.',
    [['Acceptance', 'Captured BTM + physical/model owner + traffic']],
    ['controller', 'hostapd', 'supplicant', 'tests'],
    ['reference/radio/rf-property-coverage.md'],
  ),
  '11k': entry(
    '802.11k boundary',
    'pink',
    'Qualification boundary',
    'Candidate measurements are not automatically proof of 802.11k.',
    'Native EasyMesh candidate queries and passive received scans are different observation paths. A separate captured protocol exchange is needed to claim 802.11k qualification.',
    [['Status', 'No blanket end-to-end 802.11k claim']],
    ['supplicant', 'band', 'tests'],
    ['reference/optimizer/band-steering.md'],
  ),
  '11r': entry(
    '802.11r boundary',
    'pink',
    'Qualification boundary',
    'Compiled capability is not a fast-transition acceptance result.',
    'Runtime FT requires suitable SSID security configuration and its own trace and traffic verification. Ordinary BTM results are not FT proof.',
    [['Status', 'No runtime FT qualification claimed here']],
    ['supplicant', '11v', 'tests'],
    ['reference/optimizer/band-steering.md'],
  ),
  dhcpclient: entry(
    'WLAN addressing',
    'pink',
    'Station data-plane readiness',
    'An association alone is not a working client.',
    'Clients need an IPv4 address on their WLAN path and gateway reachability. Test output separately records ownership and packet delivery.',
    [['Check', 'WLAN address + bound-interface traffic']],
    ['client', 'bridge', 'tests'],
    ['docs/test/README.md'],
  ),
  wan: entry(
    'VM networking',
    'amber',
    'Named appliance · LXD networking',
    'Host access and wireless client traffic are distinct paths.',
    'Each named VM has its own storage and host-facing ports. LXD management networking exposes the UI while native mesh bridges carry the wireless traffic being measured.',
    [
      ['Host access', 'Per-VM port forwarding'],
      ['Data plane', 'WLAN → fronthaul → backhaul → br-lan'],
    ],
    ['gateway', 'bridge', 'tests'],
    ['docs/build/vm.md', 'docs/operations.md'],
  ),
  medium: entry(
    'Simulated RF plane',
    'purple',
    'Shared guest kernel + userspace daemon',
    'Simulated radios and propagation; real native Wi-Fi software.',
    'hwsim transports frames and TX outcomes over generic netlink. wmediumd applies frequency-qualified directional link conditions. Traffic, retries and modeled airtime remain distinct observations.',
    [
      ['Participants', '15 mesh PHYs + 100 client PHYs'],
      ['Boundary', 'Not calibrated real-world PHY capacity'],
    ],
    ['hwsim', 'wmediumd', 'configurator', 'console'],
    ['reference/radio/virtual-rf-assessment.md'],
  ),
  hwsim: entry(
    'mac80211_hwsim',
    'purple',
    'Patched Linux radio driver',
    'Provides Linux Wi-Fi radios, receive contexts and native counters.',
    'Home/scan receive contexts allow beacon discovery. Survey reporting exposes qualified modeled busy time; absent or stale measurements must not be interpreted as zero utilization.',
    [
      ['Stack', 'cfg80211 → mac80211 → hwsim'],
      ['Identity', 'PHY, VIF and frequency are distinct'],
    ],
    ['radios', 'wmediumd', 'band'],
    ['reference/radio/virtual-rf-assessment.md'],
  ),
  wmediumd: entry(
    'wmediumd',
    'purple',
    'Multichannel frame-delivery model',
    'Maintains directional radio-pair conditions and real packet outcomes.',
    'SNR, loss, receive visibility, actual retries and modeled airtime are observable. A configured SNR is a stimulus; native RCPI and delivered traffic are separate evidence.',
    [
      ['Controls', 'Atomic generation + exact readback'],
      ['Load', 'Modeled occupancy; not an arbitrary capacity score'],
    ],
    ['hwsim', 'configurator', 'console'],
    ['reference/radio/virtual-rf-assessment.md'],
  ),
  configurator: entry(
    'RF configurator',
    'green',
    'Geometry → atomic RF controls',
    'Compiles rooms into frequency-qualified propagation and presence.',
    'Movement and walls change the simulated medium. The configurator does not directly choose client associations or pretend that an optimizer command succeeded.',
    [
      ['Input', 'Rooms, movement, walls, presence'],
      ['Apply', 'Control socket + generation + readback'],
    ],
    ['room', 'wmediumd', 'optimizer'],
    ['reference/rooms/architecture.md'],
  ),
  console: entry(
    'wmediumd Console NG',
    'green',
    'Read-only medium explorer',
    'Explore radios, pair conditions, packet outcomes and RF provenance.',
    'Names, frequencies, SNR, survey and packet counters expose the medium boundary. Detailed inspection is demand-driven; static Pages does not run the observer service.',
    [
      ['Guest port', '8090'],
      ['Mode', 'Observer only'],
    ],
    ['wmediumd', 'hwsim', 'room'],
    ['docs/wmediumd-console-ng.md'],
  ),
  optimizer: entry(
    'External optimizer',
    'green',
    'Observe → decide → verify',
    'Explicit policy consumes fresh native evidence, not hidden world truth.',
    'Policy enforces completeness, eligibility, dwell, hold and cooldown. Native load balancing compares quieter channels; counter pressure can veto load steering, while weak-signal rescue remains separately qualified.',
    [
      ['Load hold', '10 s'],
      ['Signal hold', '5 s in guarded-load qualification'],
      ['Safety', 'Stale or missing evidence means no action'],
    ],
    ['database', 'steer', 'band', 'tests'],
    ['reference/radio/rf-property-coverage.md'],
  ),
  steer: entry(
    'Native steering adapter',
    'green',
    'Exact station + target BSSID',
    'Submits a bounded native command and verifies the outcome.',
    'The adapter does not force association using geometry. Timings distinguish policy waits, command acceptance and actual client convergence.',
    [['Native result', 'BTM + client association + model + traffic']],
    ['controller', '11v', 'optimizer'],
    ['reference/optimizer/README.md'],
  ),
  band: entry(
    'Received-scan band policy',
    'green',
    '2.4 → 5 → 6 GHz eligibility',
    'Uses native client-received scans and explicit security/capability checks.',
    'Dedicated rooms exercise band upgrades and opposing AP/band movement. Setup may select an initial band, but timed steering uses native BTM. Saved supplicant settings are restored on exit.',
    [
      ['Evidence', 'Fresh same-direction serving/candidate signal'],
      ['Boundary', 'Not calibrated throughput or universal 6-GHz eligibility'],
    ],
    ['supplicant', 'hwsim', 'optimizer', 'tests'],
    ['reference/optimizer/band-steering.md'],
  ),
  room: entry(
    'Interactive room',
    'green',
    'Guest :8891 · static sandbox here',
    'Geometry, playback, client presence and RF inspection in one view.',
    'A live VM applies the selected room to its lab and observes native convergence. The public viewer instead previews geometry and scenarios locally; no live optimizer, BTM or test result is fabricated.',
    [
      ['Default', '20 active clients; 100 provisioned'],
      ['Public mode', 'Disconnected, no API calls'],
      ['Features', 'Play, drag, room selection, RF guide, fullscreen'],
    ],
    ['configurator', 'optimizer', 'console'],
    ['docs/live-room-demo/README.md', 'reference/rooms/catalog.md'],
  ),
  tests: entry(
    'Qualification gates',
    'green',
    'Bounded tests, explicit evidence',
    'A green UI or accepted command is not enough.',
    'Tests compare kernel association, native model, traffic, freshness and service identity, and verify cleanup. Blocked steps and preflight-only checks never count as completed campaigns.',
    [
      ['Pressure', 'Fresh veto versus held, non-actuating shadow'],
      ['Rescue', 'Captured BTM despite real counter pressure'],
      ['Scope', 'Bounded passes are not a new full suite or soak'],
    ],
    ['optimizer', 'state', 'client'],
    ['docs/test/README.md', 'reference/radio/rf-property-coverage.md'],
  ),
  state: entry(
    'Evidence and limits',
    'blue',
    'Pinned source documentation',
    'Inspect documented results, not a live status dashboard.',
    'The pinned revision records bounded prpl pressure and rescue passes and retained earlier failures. Cross-run repeatability, clean-source suite acceptance and long-duration qualification remain separate gates.',
    [
      ['Snapshot', revision.slice(0, 7)],
      ['Rescue verification', '1.918 s in one bounded prpl run'],
      ['No claim', 'New all-green catalog or long soak'],
    ],
    ['tests', 'optimizer', 'room'],
    ['reference/radio/rf-property-coverage.md'],
  ),
};
