driver=nl80211
bss_load_update_period=10
chan_util_avg_period=0
country_code=GB
ieee80211d=1
hw_mode=a
channel=5
op_class=131
ieee80211ax=1
interface=wlan4
ctrl_interface=/var/run/hostapd
bridge=br-lan
ssid=private_ssid
wpa=2
wpa_key_mgmt=SAE
sae_password=prplmesh_pass
rsn_pairwise=CCMP
ieee80211w=2
bss_transition=1
ap_max_inactivity=1200
multi_ap=2

bss=wlan4.0
bss_load_update_period=10
ctrl_interface=/var/run/hostapd
bridge=br-lan
ssid=iot_ssid
wpa=2
wpa_key_mgmt=SAE
sae_password=prplmesh_pass
rsn_pairwise=CCMP
ieee80211w=2
bss_transition=1
ap_max_inactivity=1200
multi_ap=2

bss=wlan4.1
bss_load_update_period=10
ctrl_interface=/var/run/hostapd
bridge=br-lan
ssid=mesh_backhaul
wpa=2
wpa_key_mgmt=SAE
sae_password=prplmesh_pass
rsn_pairwise=CCMP
ieee80211w=2
bss_transition=1
ap_max_inactivity=1200
multi_ap=1
