driver=nl80211
country_code=GB
ieee80211d=1
hw_mode=a
channel=36
ieee80211n=1
ieee80211ac=1
interface=wlan2
ctrl_interface=/var/run/hostapd
bridge=br-lan
ssid=private_ssid
wpa=2
wpa_key_mgmt=WPA-PSK
wpa_passphrase=prplmesh_pass
rsn_pairwise=CCMP
bss_transition=1
ap_max_inactivity=1200
multi_ap=2

bss=wlan2.0
ctrl_interface=/var/run/hostapd
bridge=br-lan
ssid=iot_ssid
wpa=2
wpa_key_mgmt=WPA-PSK
wpa_passphrase=prplmesh_pass
rsn_pairwise=CCMP
bss_transition=1
ap_max_inactivity=1200
multi_ap=2

bss=wlan2.1
ctrl_interface=/var/run/hostapd
bridge=br-lan
ssid=mesh_backhaul
wpa=2
wpa_key_mgmt=WPA-PSK
wpa_passphrase=prplmesh_pass
rsn_pairwise=CCMP
bss_transition=1
ap_max_inactivity=1200
multi_ap=1
