driver=nl80211
country_code=US
ieee80211d=1
hw_mode=a
channel=5
op_class=131
ieee80211ax=1
interface=wlan4
ctrl_interface=/var/run/hostapd
bridge=br-lan
ssid=prplmesh
wpa=2
wpa_key_mgmt=SAE
sae_password=prplmesh_pass
rsn_pairwise=CCMP
ieee80211w=2
bss_transition=1
multi_ap=3

bss=wlan4.0
ctrl_interface=/var/run/hostapd
bridge=br-lan
ssid=prplmesh
wpa=2
wpa_key_mgmt=SAE
sae_password=prplmesh_pass
rsn_pairwise=CCMP
ieee80211w=2
bss_transition=1
multi_ap=3
