ctrl_interface=/var/run/wpa_supplicant
update_config=0
country=US

network={
    ssid="prplmesh"
    psk="prplmesh_pass"
    key_mgmt=@KEY_MGMT@
    frequency=@FREQUENCY@
    scan_freq=@FREQUENCY@
    ieee80211w=1
}
