ctrl_interface=/var/run/wpa_supplicant
update_config=0
country=GB

network={
    ssid="mesh_backhaul"
    psk="prplmesh_pass"
    key_mgmt=WPA-PSK
    frequency=5180
    scan_freq=5180
    bssid=@TARGET_BSSID@
    multi_ap_backhaul_sta=1
    ieee80211w=1
}
