package main

import (
	"context"
	"flag"
	"fmt"
	"log"
	"net"
	"net/http"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/boardfarmdevs/meta-cmf-bananapi-vcpe/gen/wmediumd/observer/internal/artifacts"
	"github.com/boardfarmdevs/meta-cmf-bananapi-vcpe/gen/wmediumd/observer/internal/httpapi"
	"github.com/boardfarmdevs/meta-cmf-bananapi-vcpe/gen/wmediumd/observer/internal/identity"
	"github.com/boardfarmdevs/meta-cmf-bananapi-vcpe/gen/wmediumd/observer/internal/state"
	"github.com/boardfarmdevs/meta-cmf-bananapi-vcpe/gen/wmediumd/observer/internal/wmdproto"
	consoleweb "github.com/boardfarmdevs/meta-cmf-bananapi-vcpe/gen/wmediumd/observer/web"
)

func main() {
	listen := flag.String("listen", "127.0.0.1:8890", "HTTP listen address")
	socket := flag.String("socket", "/run/meta-cmf-wmediumd/observer/telemetry.sock", "read-only wmediumd observer/telemetry socket")
	enableControl := flag.Bool("enable-control", false, "explicitly enable typed, generation-checked controls")
	controlSocket := flag.String("control-socket", "/run/wmediumd-control.sock", "writable wmediumd socket (opened only with --enable-control)")
	poll := flag.Duration("poll", 2*time.Second, "snapshot polling interval")
	timeout := flag.Duration("timeout", 2*time.Second, "read-only socket request timeout")
	config := flag.String("config", "/run/meta-cmf-wmediumd/wmediumd.cfg", "generated startup configuration to hash")
	pidFile := flag.String("pid-file", "/run/meta-cmf-wmediumd/wmediumd.pid", "wmediumd PID file used to identify and hash its binary")
	daemonManifest := flag.String("daemon-manifest", "/run/meta-cmf-wmediumd/wmediumd-binary.sha256", "PID-qualified daemon hash manifest generated by the launcher")
	identityInventory := flag.String("identity-inventory", "/run/meta-cmf-wmediumd/identity-inventory.json", "optional generated radio identity inventory")
	flag.Parse()

	if *poll < 250*time.Millisecond {
		log.Fatal("--poll must be at least 250ms")
	}
	if *timeout <= 0 {
		log.Fatal("--timeout must be positive")
	}
	if *enableControl && (*controlSocket == "" || *controlSocket == *socket) {
		log.Fatal("--control-socket must name a distinct writable socket")
	}
	host, _, err := net.SplitHostPort(*listen)
	if err != nil {
		log.Fatalf("invalid --listen address: %v", err)
	}
	ip := net.ParseIP(host)
	loopback := host == "localhost" || ip != nil && ip.IsLoopback()
	if !loopback {
		log.Printf("WARNING: serving lab telemetry (and any explicitly enabled controls) on non-loopback address %s; use an authenticated reverse proxy for shared networks", *listen)
	}

	store := state.New()
	client := wmdproto.NewClient(*socket)
	client.Timeout = *timeout
	inspector := &artifacts.Inspector{ConfigPath: *config, PIDFile: *pidFile, DaemonManifest: *daemonManifest}
	identityLoader := identity.Loader{Path: *identityInventory}

	ctx, cancel := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer cancel()
	refresh := make(chan struct{}, 1)
	triggerRefresh := func() {
		select {
		case refresh <- struct{}{}:
		default:
		}
	}
	go collect(ctx, client, inspector, identityLoader, store, *poll, refresh)

	options := make([]httpapi.Option, 0, 1)
	if *enableControl {
		controller := wmdproto.NewController(*controlSocket, *timeout, triggerRefresh)
		options = append(options, httpapi.WithController(controller))
		log.Printf("WARNING: typed control mode enabled on %s; instance and generation checks remain mandatory", *controlSocket)
	}

	server := &http.Server{
		Addr:              *listen,
		Handler:           httpapi.New(store, consoleweb.Assets, options...),
		ReadHeaderTimeout: 5 * time.Second,
		IdleTimeout:       60 * time.Second,
		MaxHeaderBytes:    32 * 1024,
	}
	go func() {
		<-ctx.Done()
		shutdownCtx, shutdownCancel := context.WithTimeout(context.Background(), 5*time.Second)
		defer shutdownCancel()
		_ = server.Shutdown(shutdownCtx)
	}()

	log.Printf("wmediumd Console listening on http://%s (observer socket %s; controls enabled=%t)", *listen, *socket, *enableControl)
	if err := server.ListenAndServe(); err != nil && err != http.ErrServerClosed {
		log.Fatal(err)
	}
}

func collect(ctx context.Context, client *wmdproto.Client, inspector *artifacts.Inspector, identityLoader identity.Loader, store *state.Store, interval time.Duration, refresh <-chan struct{}) {
	collectOnce := func() {
		snapshot, err := client.Snapshot(ctx)
		if err != nil {
			store.UpdateError(err)
			return
		}
		snapshot.Artifacts = inspector.Inspect()
		identityLoader.Apply(&snapshot)
		store.Update(snapshot)
	}
	collectOnce()
	ticker := time.NewTicker(interval)
	defer ticker.Stop()
	for {
		select {
		case <-ctx.Done():
			return
		case <-ticker.C:
			collectOnce()
		case <-refresh:
			collectOnce()
		}
	}
}

func init() {
	flag.CommandLine.SetOutput(os.Stderr)
	flag.Usage = func() {
		fmt.Fprintf(flag.CommandLine.Output(), "wmediumd Console — live medium telemetry with read-only defaults\n\nUsage: %s [options]\n", os.Args[0])
		flag.PrintDefaults()
	}
}
