package main

import (
	"context"
	"flag"
	"fmt"
	"log"
	"net"
	"net/http"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/boardfarmdevs/meta-cmf-bananapi-vcpe/gen/wmediumd/observer/internal/artifacts"
	"github.com/boardfarmdevs/meta-cmf-bananapi-vcpe/gen/wmediumd/observer/internal/explorer"
	"github.com/boardfarmdevs/meta-cmf-bananapi-vcpe/gen/wmediumd/observer/internal/httpapi"
	"github.com/boardfarmdevs/meta-cmf-bananapi-vcpe/gen/wmediumd/observer/internal/state"
	consoleweb "github.com/boardfarmdevs/meta-cmf-bananapi-vcpe/gen/wmediumd/observer/web"
)

func main() {
	listen := flag.String("listen", "127.0.0.1:8890", "HTTP listen address")
	socket := flag.String("socket", "/run/meta-cmf-wmediumd/observer/telemetry.sock", "read-only wmediumd observer/telemetry socket")
	enableControl := flag.Bool("enable-control", false, "deprecated: ignored; Console NG is always read-only")
	flag.String("control-socket", "", "deprecated: ignored; no writable socket is opened")
	poll := flag.Duration("poll", 2*time.Second, "snapshot polling interval")
	timeout := flag.Duration("timeout", 2*time.Second, "read-only socket request timeout")
	config := flag.String("config", "/run/meta-cmf-wmediumd/wmediumd.cfg", "generated startup configuration to hash")
	pidFile := flag.String("pid-file", "/run/meta-cmf-wmediumd/wmediumd.pid", "wmediumd PID file used to identify and hash its binary")
	daemonManifest := flag.String("daemon-manifest", "/run/meta-cmf-wmediumd/wmediumd-binary.sha256", "PID-qualified daemon hash manifest generated by the launcher")
	identityInventory := flag.String("identity-inventory", "/run/meta-cmf-wmediumd/identity-inventory.json", "optional generated radio identity inventory")
	classic := flag.Bool("classic", false, "deprecated: ignored; Console NG replaces the classic UI")
	roomURL := flag.String("room-url", "http://127.0.0.1:8891", "trusted room service base URL; empty disables room correlation")
	surveyStatus := flag.String("survey-status", "/run/wmdcfg-survey.json", "cached survey bridge status; empty disables survey correlation")
	flag.Parse()

	if *poll < time.Second {
		log.Fatal("Console NG --poll must be at least 1s")
	}
	if *timeout <= 0 {
		log.Fatal("--timeout must be positive")
	}
	if *classic || *enableControl {
		log.Print("DEPRECATED: classic UI and console controls are retired; starting read-only Console NG")
	}
	host, _, err := net.SplitHostPort(*listen)
	if err != nil {
		log.Fatalf("invalid --listen address: %v", err)
	}
	ip := net.ParseIP(host)
	loopback := host == "localhost" || ip != nil && ip.IsLoopback()
	if !loopback {
		log.Printf("WARNING: serving lab telemetry on non-loopback address %s; use an authenticated reverse proxy for shared networks", *listen)
	}

	store := state.New()
	inspector := &artifacts.Inspector{ConfigPath: *config, PIDFile: *pidFile, DaemonManifest: *daemonManifest}

	ctx, cancel := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer cancel()
	runtime, runtimeErr := explorer.New(explorer.Config{Socket: *socket, Inventory: *identityInventory, Survey: *surveyStatus, RoomURL: *roomURL, Poll: *poll, Timeout: *timeout, Inspector: inspector}, store)
	if runtimeErr != nil {
		log.Fatal(runtimeErr)
	}
	go runtime.Run(ctx)
	handler := explorer.NewHandler(runtime, consoleweb.Assets, httpapi.New(store, consoleweb.Assets))
	server := &http.Server{
		Addr:              *listen,
		Handler:           handler,
		ReadHeaderTimeout: 5 * time.Second,
		IdleTimeout:       60 * time.Second,
		MaxHeaderBytes:    32 * 1024,
	}
	go func() {
		<-ctx.Done()
		shutdownCtx, shutdownCancel := context.WithTimeout(context.Background(), 5*time.Second)
		defer shutdownCancel()
		_ = server.Shutdown(shutdownCtx)
	}()

	log.Printf("wmediumd Console NG listening on http://%s (observer socket %s; read-only)", *listen, *socket)
	if err := server.ListenAndServe(); err != nil && err != http.ErrServerClosed {
		log.Fatal(err)
	}
}

func init() {
	flag.CommandLine.SetOutput(os.Stderr)
	flag.Usage = func() {
		fmt.Fprintf(flag.CommandLine.Output(), "wmediumd console ng — read-only interactive medium explorer\n\nUsage: %s [options]\n", os.Args[0])
		flag.PrintDefaults()
	}
}
